# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=seqtool

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure:  "Rm7FkPKJmeNKKu7jeN9asFWIxILeNC8//GyQZ8SCmYll70KMga2N6WK9Lu11jKt+UK9wJ3o2zrb+G0wItag1LGDOZIcQvqhB/3vp2oh8nVU1GO86fh89hObzKIfZQLsd0fzcUFayuxI2R7fEs3de45nNmvA1hoqg89rFSSyKhTmFfRWRWAYsywjT2MwWOnw/KgQDHBfGN/k//M8JgZ9hwf/hJi6MiKA/EJOO+xedkcg1P+MAaW3ctKiypS+Z7ZdxgFXdvSoYClrYg0AmPBNC5iGh7K/K0xYozWBmco3V0O4wkAS5k4cIT6GGtbHuyNDn6GIl7BotIDpTwE0vHDZH0y2Dwq3aPyrJVThImqRqDcmlwItSeEr7L2W/pa9JW1lAac46SqufmYcp27+y7lv6N14KfHzVkP9VjC8YUGyal6lhmCy4XnfXbjb3fgZv4aldEaN2q6QfDEJhubHCbG/lqw3rqKQTVUDGDDhRf70oYYhRW9A/TTJazHx32KBVvC4PcvZ1/mUnZsfDEtlDaL7HGDLeBh4Il0hKDPOxB3AqNlRQyi3WqnKw5wY/N6xKMGVvsciGSauJPkT16yRsL1TCzxP9Q/AndfMnNmq5dPCG8XSUSJu06eGfzsrQ5VuaukVqEvkf2sHg0jNvrE26IHQ9PnMmK7jHhDjSnULFSjZ24nU="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
