[package]
name = "seqtool"
version = "0.2.3"
authors = ["<markschl19@gmail.com>"]
description = "General purpose tool for reading, modifying and writing biological sequences."
license = "MIT"
repository = "https://github.com/markschl/seq_io"
documentation = "https://docs.rs/seq_io"
readme = "README.md"

[dependencies]
docopt = "0.8"
bio = "0.17"
seq_io = "0.2.4"
thread_io = { version="0.1", path="src/thread_io" }
crossbeam = "0.3"
lazy_static = "1.0"
regex = "0.2"
csv = "1.0.0-beta.5"
itertools = "0.7"
bit-vec = "0.5"
vec_map = "0.8"
rand = "0.4"
flate2 = "1.0"
bzip2 = "0.3"
lz4 = "1.22"
zstd = "0.4"
twoway = "0.1"
memchr = "2.0"
fxhash = "0.2"
textwrap = "0.10"
meval = "0.1"
exprtk_rs = { version = "0.0.4", optional = true, features = [
  "comments", "break_continue", "sc_andor", "return_statement",
  "enhanced_features", "superscalar_unroll"
 ] }
bytecount = "0.3"
clippy = { version = "0.0.195", optional = true }
maplit = "1.0"
pattern_matching = { path = "src/pattern_matching", version = "0.1.1" }
ref_slice = "1.1"

[dev-dependencies]
assert_cli = "0.5"
tempdir = "0.3"

[features]
default = []
nightly = ["twoway/pcmp"]
exprtk = ["exprtk_rs"]

[profile.release]
lto = true
panic = "abort" # smaller & faster binary
