[package]
name = "pattern_matching"
version = "0.1.1"
authors = ["marcschl <ms201@gmx.net>"]

[dependencies]
bio = "*"

[dev-dependencies]
bio = "*"

[profile.bench]
#lto = true

[dependencies.num-traits]
version = "^0.2.5"
default-features = false
